### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MishterKirby**
Changed wording.

### CODE REVIEW

**Comment by ittat** [comment]
@MishterKirby Hi, I have successfully ported the current-gecko to onyx, so I think I plan to stop the old B2G project for onyx.
https://github.com/b2gOS

**Comment by MishterKirby** [comment]
Okay, then. Glad I could help out while it lasted!

**Review by ittat — APPROVED** [review]

**Comment by ittat** [comment]
@MishterKirby  Thank you！
And Have you ported the "old" B2G to your device?

**Comment by MishterKirby** [comment]
No, the build system was giving me problems for some reason.

**Comment by ittat** [comment]
> No, the build system was giving me problems for some reason.

All right, if you meet any issues during building source, I am willing to solve them with you. good luck:)

**Comment by ittat** [comment]
@MishterKirby  I noticed that you tried to build current-gecko for your device [B2G](https://github.com/MishterKirby/B2G).

And I built an experimental project called [lineage-b2g](https://github.com/lineage-b2g), in order to easily port B2G to devices that can support Lineage-17.1. It is worth noting that the project can build completed on simulator now. However, due to limited time, I did not verify the reliability of the code. At the same time, it will not be supported by the B2G community.

**Pull request merged**
